# Generated by Django 4.2.7 on 2024-03-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('HeadOfDepartment', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cnic',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_no',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester_No', models.PositiveIntegerField(default=0)),
                ('DepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.semester')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.department'),
        ),
    ]
