# Generated by Django 4.2.7 on 2024-03-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_parent_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_no',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
