# Generated by Django 4.2.7 on 2024-04-29 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
