# Generated by Django 4.2.7 on 2024-04-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, default='', related_name='students', to='core.teacher'),
        ),
    ]
