# Generated by Django 4.2.7 on 2024-04-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_student_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ManyToManyField(blank=True, default='1', related_name='semester', to='core.semester'),
        ),
    ]
