# Generated by Django 4.2.7 on 2024-04-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='da',
            field=models.CharField(default='abcd', max_length=100),
        ),
    ]
