# Generated by Django 4.2.7 on 2024-04-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_student_da'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='da',
        ),
    ]
