# Generated by Django 4.2.7 on 2024-04-30 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_student_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.semester'),
        ),
    ]
