# Generated by Django 4.2.7 on 2024-04-30 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_student_semester_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
    ]
