# Generated by Django 4.2.7 on 2024-07-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='Semester_No',
            field=models.CharField(default=1, max_length=4),
        ),
    ]
